//array de productos CONSOLAS
const productos = [{ id:1, nombre :"CONSOLA 1TB SLIM CUH-2215B",
imagen:"multimedia/imagenes/ps4slim.jpg" ,
precio: 800,
stock:5},
{ id:2, nombre: "PS4 CONSOLA 1TB SLIM MEGA PACK 18 RANDC-GOT-GO",
imagen:"multimedia/imagenes/ps4slimmegapack.jpg" ,
precio: 900,
stock:10},
{ id:3,nombre: "PS5 STANDARD EDITION 1TB US ",
imagen:"multimedia/imagenes/ps5standar.png",
precio: 1000, 
stock:6},
{ id:4, nombre: "PS5 STANDARD EDITION 1TB JPN", 
imagen:"multimedia/imagenes/ps5standar.png",
precio: 1100, 
stock:8},
{ id: 5, nombre:"NINTENDO SWITCH OLED 64GB NEON", 
imagen:"multimedia/imagenes/nintendoswitcholed-neon.jpg",
precio:700, 
stock:11},
{ id:6, nombre:"NINTENDO SWITCH CONSOLA 64GB NEON", 
imagen:"multimedia/imagenes/nintendoswitch-neon.png",
precio:600, 
stock:13},
{ id:7, nombre:"NINTENDO SWITCH OLED 64GB BLANCA", 
imagen: "multimedia/imagenes/nintendoswitcholed-blanca.png",
precio:700, 
stock:1},
{ id:8, nombre:"CONSOLA XBOX ONE SERIES X STANDARD JPN",
imagen:"multimedia/imagenes/xboxonex.jpg",
precio:800, 
stock:5},];

const carrito = [];
